force-app/main/default/objects/Trigger__mdt/Trigger__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata to represent triggers for the trigger framework</description>
    <label>Trigger</label>
    <pluralLabel>Triggers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox determining if the trigger will be active to execute</description>
    <inlineHelpText>Set whether trigger classes associated to this trigger will be executed</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Class__mdt/Trigger_Class__mdt.object-meta.xml
<CustomObject>
    <description>Class to be triggered in trigger context, associated to a Trigger mdt record</description>
    <label>Trigger Class</label>
    <pluralLabel>Trigger Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Class__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the class to be run in trigger context</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Class__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Numerical sort order designation, with lower numbers executed ahead of higher numbers</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trigger_Class__mdt/fields/Trigger__c.field-meta.xml
<CustomField>
    <fullName>Trigger__c</fullName>
    <label>Trigger</label>
    <referenceTo>Trigger__mdt</referenceTo>
    <relationshipLabel>Trigger Classes</relationshipLabel>
    <relationshipName>Trigger_Classes</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/TriggerHandler.cls
public with sharing class TriggerHandler {
    private String sObjectName;
    private List<String> triggerIgnore = new List<String>();

    List<Trigger_Class__mdt> triggerClasses {
        get {
            if(triggerClasses == null) {
                triggerClasses = getTriggerClasses();
            }
            return triggerClasses;
        }
        set;
    }

    List<Trigger_Class__mdt> getTriggerClasses() {
        Trigger__mdt triggerMeta = Trigger__mdt.getInstance(sObjectName);
        if(triggerMeta != null) {
            triggerClasses = [
                SELECT Id, Class_Name__c, Is_Active__c, Sort_Order__c
                FROM Trigger_Class__mdt 
                WHERE Trigger__c = :triggerMeta.Id
                ORDER BY Sort_Order__c ASC
            ];
        }
        return triggerClasses;
    }
    
    public TriggerHandler(String sObjectName) {
        this.sObjectName = sObjectName;
    }

    public void addTriggerIgnore(String triggerName) {
        triggerIgnore.add(triggerName);
    }

    public void run() {
        if(!Trigger.isExecuting || triggerIgnore.contains(sObjectName)) {
            return;
        }

        for(Trigger_Class__mdt triggerClassMeta: triggerClasses) {
            if(triggerClassMeta.Is_Active__c) {
                ITrigger triggerClass = getClassInstance(triggerClassMeta.Class_Name__c);
                triggerClass.execute();
            }
        }
    }

    private ITrigger getClassInstance(String className) {
        Type t = Type.forName(className);

        if(t == null) {
            throw new TypeException('No class found');
        }

        Object triggerClass = t.newInstance();
        if (!(triggerClass instanceof ITrigger)) {
            throw new IllegalArgumentException('Trigger class must implement ITrigger');
        } 
        return (ITrigger) triggerClass;
    }

    // add methods to consider trigger context, i.e. 
    // Trigger.isBefore, Trigger.isAfter
    // Trigger.operationType
}