force-app/main/default/objects/Trigger_Class__mdt/Trigger_Class__mdt.object-meta.xml
<CustomObject>
    <description>Class to be triggered in trigger context, associated to a Trigger mdt record</description>
    <label>Trigger Class</label>
    <pluralLabel>Trigger Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Class__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the class to be run in trigger context</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Class__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Numerical sort order designation, with lower numbers executed ahead of higher numbers</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerTest.cls
@IsTest
public with sharing class TriggerHandlerTest {
    private static final String SOBJECT_TYPE = 'Account';
    private static Boolean testRunWasSuccessful = false;
    private static Integer triggerEventsConsumed = 0;

    @IsTest
    static void noClassFound() {
        Exception caughtException;

        Test.startTest();
        try {
            Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata('ClassDoesntExist');

            TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
            handler.triggerClasses = new List<Trigger_Class__mdt> {
                triggerClassMetadata
            };
            handler.getClassInstance(triggerClassMetadata.Class_Name__c);
        } catch(Exception e) {
            caughtException = e;
        }
        Test.stopTest();

        System.assertNotEquals(null, caughtException, 'Exception is caught');
        System.assertEquals('No class found', caughtException.getMessage(), 'Exception message');
        System.assert(caughtException instanceof TypeException);
    }

    @IsTest
    static void classDoesntImplementITriggerInterface() {
        Exception caughtException;

        Test.startTest();
        try {
            Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata(ClassWithoutInterface.class.getName());

            TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
            handler.triggerClasses = new List<Trigger_Class__mdt> {
                triggerClassMetadata
            };
            handler.getClassInstance(triggerClassMetadata.Class_Name__c);
        } catch(Exception e) {
            caughtException = e;
        }
        Test.stopTest();

        System.assertNotEquals(null, caughtException, 'Exception is caught');
        System.assertEquals('Trigger class must implement ITrigger', caughtException.getMessage(), 'Exception message');
        System.assert(caughtException instanceof TypeException);
    }

    @IsTest
    static void noTriggerOperationsSet() {
        Exception caughtException;

        Test.startTest();
        try {
            Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata(
                ClassWithoutTriggerOperations.class.getName()
            );

            TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
            handler.triggerClasses = new List<Trigger_Class__mdt> {
                triggerClassMetadata
            };
            handler.execute(new ClassWithoutTriggerOperations());
        } catch(Exception e) {
            caughtException = e;
        }
        Test.stopTest();

        System.assertNotEquals(null, caughtException, 'Exception is caught');
        System.assertEquals('At least one trigger operation must be set', caughtException.getMessage(), 'Exception message');
        System.assert(caughtException instanceof ListException);
    }

    @IsTest
    static void run() {
        Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata(
            ClassWithTriggerOperations.class.getName()
        );

        Test.startTest();
        TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
        handler.triggerClasses = new List<Trigger_Class__mdt> {
            triggerClassMetadata
        };
        handler.executeTriggerClasses();
        Test.stopTest();

        System.assertEquals(true, testRunWasSuccessful, 'Trigger class execution was successful');
        System.assertEquals(3, triggerEventsConsumed, 'Three trigger events consumed');
    }

    @IsTest
    static void triggerIgnore() {
        TriggerHandler.addTriggerIgnore(SOBJECT_TYPE);

        Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata(
            ClassWithTriggerOperations.class.getName()
        );

        Test.startTest();
        TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
        handler.triggerClasses = new List<Trigger_Class__mdt> {
            triggerClassMetadata
        };
        handler.run();
        Test.stopTest();

        System.assertEquals(false, testRunWasSuccessful, 'Trigger was ignored');
    }

    @IsTest
    static void triggerClassInactive() {
        TriggerHandler.addTriggerIgnore(SOBJECT_TYPE);

        Trigger_Class__mdt triggerClassMetadata = buildTriggerClassMetadata(
            ClassWithTriggerOperations.class.getName()
        );
        triggerClassMetadata.Is_Active__c = false;

        Test.startTest();
        TriggerHandler handler = new TriggerHandler(SOBJECT_TYPE);
        handler.triggerClasses = new List<Trigger_Class__mdt> {
            triggerClassMetadata
        };
        handler.run();
        Test.stopTest();

        System.assertEquals(false, testRunWasSuccessful, 'Trigger class inactive');
    }

    static Trigger_Class__mdt buildTriggerClassMetadata(String className) {

        Trigger_Class__mdt triggerClassMetadata = new Trigger_Class__mdt(
            Class_Name__c = className,
            Is_Active__c = true,
            Sort_Order__c = 0
        );

        return triggerClassMetadata;
    }

    public class ClassWithoutInterface { }

    public class ClassWithoutTriggerOperations implements ITrigger {
        public List<System.TriggerOperation> setTriggerOperations() {
            return new List<System.TriggerOperation>();
        }

        public void execute(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {}
    }

    public class ClassWithTriggerOperations implements ITrigger {
        public List<System.TriggerOperation> setTriggerOperations() {
            return new List<System.TriggerOperation> {
                System.TriggerOperation.BEFORE_INSERT,
                System.TriggerOperation.BEFORE_UPDATE,
                System.TriggerOperation.BEFORE_DELETE
            };
        }

        public void execute(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
            testRunWasSuccessful = true;
            triggerEventsConsumed += 1;
        }
    }
}